# -*- coding: utf-8 -*-
import _en
NB='&nbsp;'
b=[
('<title>'+open('diarrhee-du-voyageur.html',encoding='utf-8').read().split('<title>')[1].split('</title>')[0]+'</title>','<title>Traveler’s diarrhea — how to avoid tourista | Probaclac</title>'),
# eyebrows
('<div class="eyebrow"><span class="dot"></span>Guide voyage</div>','<div class="eyebrow"><span class="dot"></span>Travel guide</div>'),
('<div class="eyebrow"><span class="dot"></span>Zones à risque</div>','<div class="eyebrow"><span class="dot"></span>Risk zones</div>'),
('<div class="eyebrow"><span class="dot"></span>Prévention</div>','<div class="eyebrow"><span class="dot"></span>Prevention</div>'),
('<div class="eyebrow"><span class="dot"></span>Symptômes</div>','<div class="eyebrow"><span class="dot"></span>Symptoms</div>'),
('<div class="eyebrow"><span class="dot"></span>Causes</div>','<div class="eyebrow"><span class="dot"></span>Causes</div>'),
('<div class="eyebrow"><span class="dot"></span>Modes de prévention</div>','<div class="eyebrow"><span class="dot"></span>Prevention methods</div>'),
("<div class=\"eyebrow\"><span class=\"dot\"></span>L'hygiène avant tout</div>",'<div class="eyebrow"><span class="dot"></span>Hygiene first</div>'),
# hero
('<h1 class="hero__h1">Comment éviter la diarrhée du voyageur.</h1>','<h1 class="hero__h1">How to avoid traveler’s diarrhea.</h1>'),
("La diarrhée du voyageur ou tourista est une diarrhée aigüe qui affecte un grand nombre de voyageurs. Il est dit qu'entre 60 et 80% des voyageurs dans les régions tropicales, subtropicales et en voie de développement sont touchés par cette gastro-entérite pénible. Bien que le risque soit plus élevé dans ces régions, l'Organisation mondiale de la Santé (OMS) nous rappelle que l'hygiène peut laisser à désirer n'importe où, il est donc préférable de prendre ses précautions.",
 "Traveler's diarrhea or tourista is an acute diarrhea that affects a large number of travelers. It is said that between 60 and 80% of travelers in tropical, subtropical and developing regions are affected by this distressing gastroenteritis. Although the risk is higher in these areas, the World Health Organization (WHO) reminds us that hygiene can be poor anywhere, so it's best to take precautions."),
('Prévenir avec Probaclac Voyageurs','Prevent with Probaclac Travelers'),
('Voir les conseils','See the tips'),
# map
("<h2>Où risque-t-on d'attraper la tourista"+NB+"?</h2>",'<h2>Where is the risk of catching tourista?</h2>'),
("<p>Le risque est plus élevé dans les régions tropicales, subtropicales et en voie de développement — mais aucune destination n'est entièrement à l'abri.</p>",
 '<p>The risk is higher in tropical, subtropical and developing regions — but no destination is entirely safe.</p>'),
# conseils
('<h2>Conseils pour éviter la diarrhée en voyage.</h2>','<h2>Tips to avoid diarrhea while traveling.</h2>'),
('<p>Faire attention à tout ce qui est consommé : nourriture ou boisson.</p>','<p>Be careful with everything you consume: food or drink.</p>'),
("<p>Méfiez-vous de l'eau du robinet, des glaçons, et de tous les frappés glacés</p>",'<p>Beware of tap water, ice cubes, and all frozen smoothies</p>'),
('<p>Éviter la nourriture vendue dans la rue</p>','<p>Avoid street food</p>'),
('<p>S\'assurer que les aliments sont bien cuits</p>','<p>Make sure food is cooked thoroughly</p>'),
('<p>Éviter les fruits de mer</p>','<p>Avoid seafood</p>'),
("<p>Prendre garde aux fruits et légumes frais (salades), optez pour les aliments qui s'épluchent (ex. banane)</p>",'<p>Be careful with fresh fruits and vegetables (salads), opt for foods that can be peeled (e.g. bananas)</p>'),
('<p>Éviter les aliments à base de lait</p>','<p>Avoid dairy-based foods</p>'),
('<p>Éviter les oeufs</p>','<p>Avoid eggs</p>'),
# symptoms
("<h2>Quels sont les symptômes de la diarrhée du voyageur"+NB+"?</h2>",'<h2>What are the symptoms of traveler’s diarrhea?</h2>'),
('<p>La tourista fait habituellement son entrée dans les <strong>premiers 3 à 5 jours</strong> du séjour. Elle se présente le plus souvent comme une diarrhée liquide sans fièvre et sans sang.</p>',
 '<p>Tourista usually appears within the <strong>first 3 to 5 days</strong> of the stay. It most often presents as watery diarrhea without fever or blood.</p>'),
('<li>Diarrhée</li>','<li>Diarrhea</li>'),
('<li>Crampes abdominales</li>','<li>Abdominal cramps</li>'),
('<li>Nausées et vomissements <span class="note">1 sur 10 cas</span></li>','<li>Nausea and vomiting <span class="note">1 in 10 cases</span></li>'),
('<li>Fièvre <span class="note">1 sur 10 cas</span></li>','<li>Fever <span class="note">1 in 10 cases</span></li>'),
('<li>Inconfort général</li>','<li>General discomfort</li>'),
('<li>Signes de déshydratation</li>','<li>Signs of dehydration</li>'),
# causes
("<h2>Quelles sont les causes"+NB+"?</h2>",'<h2>What causes traveler’s diarrhea?</h2>'),
("<p>Plus souvent d'origine <strong>bactérienne</strong> que parasitaire ou découlant d'un virus, sa transmission se fait par voie oro-fécale. Un bon nombre de bactéries sont responsables de la contamination, la plus connue et la plus fréquente est sans contredit la <em>Escherichia coli</em> entérotoxinogène aussi connue sous sa forme abrégée de <em>E."+NB+"coli</em>.</p>",
 '<p>More often of <strong>bacterial</strong> origin than parasitic or resulting from a virus, its transmission is by the oral-fecal route. A number of bacteria are responsible for contamination, the best known and most frequent is undoubtedly enterotoxigenic <em>Escherichia coli</em> also known by its abbreviated form of <em>E.'+NB+'coli</em>.</p>'),
("<p>Le mécanisme d'action de la bactérie <em>E."+NB+"coli</em> se traduit par la production d'une entérotoxine (substance toxique qui cible les intestins) qui provoque un flux d'eau et d'électrolytes dans la lumière intestinale, ayant pour effet de ramollir les selles et d'avoir une diarrhée.</p>",
 '<p>The mechanism of action of the <em>E.'+NB+'coli</em> bacteria is the production of an enterotoxin (a toxic substance that targets the intestines) which causes a flow of water and electrolytes into the intestinal lumen, resulting in softening of the stool and diarrhea.</p>'),
("<p>Les autres bactéries causant ce maux sont la <em>Salmonelle</em>, la <em>Shigella</em>, et le <em>Campylobacter</em>. La maladie peut aussi parfois être causée, bien que moins souvent, par des parasites comme les <em>Giardia</em>, les <em>Cryptosporidium</em>, les <em>Cyclospora</em> ou par des virus tels que le rotavirus ou le norovirus.</p>",
 '<p>Other bacteria that cause this condition include <em>Salmonella</em>, <em>Shigella</em>, and <em>Campylobacter</em>. The disease can also sometimes be caused, although less often, by parasites such as <em>Giardia</em>, <em>Cryptosporidium</em>, <em>Cyclospora</em>, or by viruses such as rotavirus or norovirus.</p>'),
("<p class=\"q\">«"+NB+"Cuire les aliments, les bouillir, les éplucher ou ne pas les consommer."+NB+"»</p>",'<p class="q">“Cook food, boil it, peel it or not eat it.”</p>'),
('<div class="src">Organisation mondiale de la Santé</div>','<div class="src">World Health Organization</div>'),
# table
('<h2>Probiotiques ou vaccins oraux'+NB+'?</h2>','<h2>Probiotics or oral vaccines?</h2>'),
('<p>Deux approches préventives existent. Voici comment elles se comparent, point par point.</p>','<p>Two preventive approaches exist. Here’s how they compare, point by point.</p>'),
('<div><span class="pin"></span>Probiotiques</div>','<div><span class="pin"></span>Probiotics</div>'),
('<div>Vaccins oraux</div>','<div>Oral vaccines</div>'),
('<div class="h">Prendre à quelle fréquence'+NB+'?</div>','<div class="h">How often to take?</div>'),
('<div class="c">Une semaine avant le départ, pendant le séjour, et une semaine après le retour</div>','<div class="c">Take one week before departure, during the stay, and one week after returning</div>'),
("<div class=\"c\">2 doses à 1 semaine d'intervalle, au plus tard 2 semaines avant le départ</div>",'<div class="c">Take 2 doses 1 week apart no later than 2 weeks before departure</div>'),
('<div class="h">Nécessite une prescription'+NB+'?</div>','<div class="h">Requires a prescription?</div>'),
('<div class="c">Non</div>','<div class="c">No</div>'),
("<div class=\"c\">Non, mais doit être recommandé avec le protocole d'immunisation du Québec, avec consultation d'un professionnel de la santé. Non pour les résidents des autres provinces</div>",'<div class="c">No, but must be recommended with the Quebec immunization protocol with consultation of a health professional. No for residents of other provinces</div>'),
("<div class=\"h\">À qui s'adressent ces modes de prévention"+NB+"?</div>",'<div class="h">Who are these prevention methods aimed at?</div>'),
('<div class="c">Adolescents (12 ans et plus) et adultes. Les formules pour enfants sont recommandées pour les 1 à 3 ans et les 3 ans et plus</div>',"<div class=\"c\">Adolescents (12 years and older) and Adults. Children's formulas are recommended for ages 1 to 3 and ages 3 and up.</div>"),
('<div class="c">Adultes et enfants âgés de 2 ans et plus</div>','<div class="c">Adults and children aged 2 years and over</div>'),
('<div class="h">Conservé au réfrigérateur'+NB+'?</div>','<div class="h">Kept in the refrigerator?</div>'),
('<div class="c">Non, ne nécessite aucune réfrigération</div>','<div class="c">No, does not require refrigeration</div>'),
("<div class=\"c\">Oui, nécessite d'être réfrigéré</div>",'<div class="c">Yes, requires refrigeration</div>'),
("<div class=\"h\">Possibilité d'effets secondaires</div>",'<div class="h">Possible side effects</div>'),
('<div class="c">Possibilité de ballonnements et de gaz au début de la consommation</div>','<div class="c">Possibility of bloating and gas at the beginning of consumption</div>'),
('<div class="c">Possibilité de douleur abdominale, diarrhée, nausées, vomissements, fièvre</div>','<div class="c">Possibility of abdominal pain, diarrhea, nausea, vomiting, fever</div>'),
# hygiene
('<h2>Il vaut mieux prévenir que guérir.</h2>','<h2>Prevention is better than cure.</h2>'),
("<p>L'infection peut se transmettre d'une personne à l'autre. Quatre habitudes à garder tout au long du séjour.</p>",'<p>The infection can be transmitted from person to person. Four habits to keep throughout your stay.</p>'),
('<h3>Se laver les mains avec du savon</h3>','<h3>Wash your hands with soap</h3>'),
("<h3>Se brosser les dents avec de l'eau embouteillée</h3>",'<h3>Brushing your teeth with bottled water</h3>'),
('<h3>Prendre soin de son système immunitaire</h3>','<h3>Taking care of your immune system</h3>'),
("<h3>S'assurer de dormir convenablement</h3>",'<h3>Make sure you get adequate sleep</h3>'),
# produit
('<h2>Probaclac Voyageurs.</h2>','<h2>Probaclac Travelers.</h2>'),
("<p class=\"lead\">Une protection ciblée contre la diarrhée du voyageur — à commencer une semaine avant le départ, à poursuivre pendant le séjour et une semaine après le retour.</p>","<p class=\"lead\">Targeted protection against traveler's diarrhea — start one week before departure, continue during your stay and one week after your return.</p>"),
('<li>9 souches probiotiques + vitamine C</li>','<li>9 probiotic strains + vitamin C</li>'),
('<li>Aucune réfrigération nécessaire</li>','<li>No refrigeration required</li>'),
('<li>Sans prescription</li>','<li>No prescription needed</li>'),
('<li>Format 30 capsules · 1 par jour</li>','<li>30-capsule format · 1 per day</li>'),
('Découvrir Voyageurs','Discover Travelers'),
('Voir les études','See the studies'),
]
_en.build('diarrhee-du-voyageur.html','diarrhee-du-voyageur.html',b)
