# -*- coding: utf-8 -*-
import _en
NB='&nbsp;'
P=[
('<title>'+open('choisir.html',encoding='utf-8').read().split('<title>')[1].split('</title>')[0]+'</title>','<title>Choosing the right probiotic | Probaclac</title>'),
('<h1 class="hero__h1">Choisir le bon probiotique.</h1>','<h1 class="hero__h1">Choosing the right probiotic.</h1>'),
('Découvrez pourquoi Probaclac se démarque et trouvez la formule adaptée à votre profil — selon votre âge, votre condition ou vos allergies.','Discover why Probaclac stands out and find the formula suited to your profile — by your age, your condition or your allergies.'),
('Voir les bienfaits','See the benefits'),
('Un sérieux pharmaceutique, prouvé.','Pharmaceutical rigor, proven.'),
('Six raisons qui font de Probaclac une référence en probiotiques de grade pharmaceutique au Canada.','Six reasons that make Probaclac a benchmark in pharmaceutical-grade probiotics in Canada.'),
('Certifié NPN','NPN certified'),
('Tous nos produits sont certifiés NPN et approuvés par Santé Canada.','All our products are NPN certified and approved by Health Canada.'),
('Normes les plus élevées','Highest standards'),
('Probaclac est fabriqué selon les normes les plus élevées et contient des souches probiotiques testées cliniquement.','Probaclac is manufactured to the highest standards and contains clinically tested probiotic strains.'),
('Testé cliniquement','Clinically tested'),
('Probaclac est soumis à un contrôle de qualité rigoureux et est testé cliniquement pour démontrer les effets recherchés.','Probaclac undergoes rigorous quality control and is clinically tested to demonstrate the intended effects.'),
('20 ans de confiance','20 years of trust'),
('Probaclac est une marque de confiance depuis plus de 20 ans.','Probaclac has been a trusted brand for over 20 years.'),
('Formules avec prébiotiques','Formulas with prebiotics'),
("Probaclac contient des prébiotiques et propose des formules spécifiquement conçues en fonction de l'âge et de la condition de chacun.","Probaclac contains prebiotics and offers formulas specifically designed according to each person's age and condition."),
('Fabriqué au Québec','Made in Quebec'),
('La gamme Probaclac est fièrement fabriquée au Québec et approuvée par les Produits du Québec.','The Probaclac range is proudly made in Quebec and approved by Produits du Québec.'),
('Les bienfaits des probiotiques sur votre santé.','The benefits of probiotics for your health.'),
("Onze champs d'action documentés par la littérature scientifique — chaque catégorie renvoie aux études citées en référence.","Eleven fields of action documented by scientific literature — each category links to the studies cited in references."),
('Faciliter la digestion','Support digestion'),
('Constipation chez les personnes âgées','Constipation in the elderly'),
('Diarrhée associée aux antibiotiques','Antibiotic-associated diarrhea'),
('Voyages outre-mer','Overseas travel'),
('Ballonnements','Bloating'),
("Soutenir l'immunité",'Support immunity'),
('Infections respiratoires','Respiratory infections'),
('Infections urinaires','Urinary tract infections'),
('Vaccination chez les aînés','Vaccination in seniors'),
('Otites','Ear infections'),
("Réguler l'appétit et le poids santé",'Regulate appetite and healthy weight'),
('Obésité ou embonpoint','Obesity or overweight'),
('Troubles alimentaires','Eating disorders'),
('Diabète de type 2','Type 2 diabetes'),
('Réduire le stress psychologique','Reduce psychological stress'),
('Anxiété','Anxiety'),
('Dépression','Depression'),
('Difficultés de concentration','Difficulty concentrating'),
('Améliorer la performance cognitive','Improve cognitive performance'),
('Pertes de mémoire','Memory loss'),
('Mauvaise humeur','Low mood'),
('Protéger le cœur','Protect the heart'),
('Dyslipidémie (cholestérol sanguin)','Dyslipidemia (blood cholesterol)'),
('Hypertension artérielle','High blood pressure'),
('Prévenir les réactions auto-immunes','Prevent autoimmune reactions'),
('Allergies alimentaires','Food allergies'),
('Eczéma','Eczema'),
('Prévenir les maladies inflammatoires','Prevent inflammatory diseases'),
('Maladie de Crohn',"Crohn's disease"),
("Syndrome de l'intestin irritable",'Irritable bowel syndrome'),
('Retarder le vieillissement dermatologique','Slow skin aging'),
('Sécheresse de la peau','Dry skin'),
('Cuir chevelu','Scalp'),
('Photosensibilité','Photosensitivity'),
('Rides','Wrinkles'),
('Prévenir les carences nutritives','Prevent nutritional deficiencies'),
("Troubles du spectre de l'autisme",'Autism spectrum disorders'),
('Intolérances alimentaires','Food intolerances'),
('Ralentir les maladies dégénératives','Slow degenerative diseases'),
("Maladie d'Alzheimer","Alzheimer's disease"),
('Maladie de Parkinson',"Parkinson's disease"),
('Selon votre âge ou votre condition.','By your age or your condition.'),
('La flore intestinale évolue au fil de la vie et selon votre situation. Choisissez le produit qui vous correspond.','The intestinal flora evolves throughout life and according to your situation. Choose the product that fits you.'),
("Selon l'âge",'By age'),
('Selon la condition','By condition'),
('Enfants 1 à 3 ans','Toddlers 1 to 3 years'),
("Dès la naissance, le microbiote se développe et se diversifie. La capsule ouvrable facilite la consommation chez l'enfant.","From birth, the microbiota develops and diversifies. The openable capsule makes consumption easier for children."),
('Enfants croquables 3 ans +','Chewable kids 3 years +'),
("Dès 3 ans, le microbiote intestinal continue de se développer jusqu'à l'âge adulte.","From age 3, the intestinal microbiota continues to develop into adulthood."),
("À l'âge adulte, la composition de la flore probiotique intestinale se stabilise.","In adulthood, the composition of the intestinal probiotic flora stabilizes."),
('Après 50 ans, la concentration de bonnes bactéries, particulièrement les Bifidobactéries, diminue graduellement.','After 50, the concentration of good bacteria, particularly Bifidobacteria, gradually decreases.'),
('Formule assurant un confort intestinal durant les voyages.','Formula ensuring intestinal comfort while traveling.'),
('Diarrhée · antibiotiques','Diarrhea · antibiotics'),
("Réduction de la diarrhée associée à la prise d'antibiotiques.",'Reduces diarrhea associated with taking antibiotics.'),
('Problèmes intestinaux aigus','Acute intestinal problems'),
('Concentration élevée pour les problèmes intestinaux aigus.','High concentration for acute intestinal problems.'),
('Côlon irritable (SCI)','Irritable bowel (IBS)'),
('Syndrome du côlon irritable','Irritable bowel syndrome'),
('Soulage gaz, ballonnements et inconforts. 10 milliards de cellules actives.','Relieves gas, bloating and discomfort. 10 billion active cells.'),
('Réduction de la diarrhée associée aux antibiotiques et de la diarrhée infectieuse aiguë.','Reduces antibiotic-associated diarrhea and acute infectious diarrhea.'),
("Supporte l'équilibre bactérien du tractus urinaire.",'Supports the bacterial balance of the urinary tract.'),
('Candidose vulvo-vaginale','Vulvovaginal candidiasis'),
('Réduit les signes de candidose vulvo-vaginale avec la souche Rosella.','Reduces the signs of vulvovaginal candidiasis with the Rosella strain.'),
('Aide à réduire la récurrence de la vaginose bactérienne.','Helps reduce the recurrence of bacterial vaginosis.'),
('Comprendre la différence.','Understand the difference.'),
('Les probiotiques','Probiotics'),
('Des micro-organismes vivants qui, ingérés en quantité suffisante, exercent des effets positifs sur la santé du microbiote.','Living micro-organisms which, ingested in sufficient quantities, have positive effects on the health of the microbiota.'),
('Les prébiotiques','Prebiotics'),
("Des fibres végétales que nous ne digérons pas pendant leur passage dans l'estomac. Elles servent de nourriture aux bifidobactéries.",'Plant fibers that we do not digest as they pass through the stomach. They serve as food for bifidobacteria.'),
('Les formules Probaclac contiennent des prébiotiques pour nourrir et soutenir les bonnes bactéries de votre flore intestinale.','Probaclac formulas contain prebiotics to nourish and support the good bacteria of your intestinal flora.'),
('Et les yogourts probiotiques dans tout ça'+NB+'?','And what about probiotic yogurts?'),
("Les yogourts probiotiques réfrigérés posent plusieurs défis de fiabilité"+NB+": la chaîne de température, la durée de conservation et les conditions de fabrication rendent difficile la garantie d'un nombre suffisant de bactéries vivantes au moment de la consommation.",'Refrigerated probiotic yogurts pose several reliability challenges: the temperature chain, shelf life and manufacturing conditions make it difficult to guarantee a sufficient number of live bacteria at the time of consumption.'),
("La date de fabrication ne garantit pas la viabilité des souches jusqu'à la péremption"+NB+"; plusieurs contiennent aussi du sucre ajouté, ce qui peut nuire à leur efficacité.",'The manufacturing date does not guarantee the viability of the strains until expiration; many also contain added sugar, which can hinder their effectiveness.'),
('Des probiotiques sans allergènes.','Allergen-free probiotics.'),
('Tout au long de la production, les allergènes alimentaires prioritaires sont évités. Probaclac est la référence pour des probiotiques sans protéines laitières, sans gluten, sans soya et sans tous les allergènes classiques.*','Throughout production, priority food allergens are avoided. Probaclac is the reference for probiotics without dairy proteins, gluten, soy and all classic allergens.*'),
('Sans gluten','Gluten free'),
('Sans soya','Soy free'),
('Sans lactose','Lactose free'),
('Capsules végétales','Vegetable capsules'),
('Pourquoi opter pour Probaclac'+NB+'?','Why choose Probaclac?'),
('Multi-souches','Multi-strain'),
('Grade pharmaceutique','Pharmaceutical grade'),
('Formulations spécifiques','Specific formulations'),
('Contient des prébiotiques','Contains prebiotics'),
('Références scientifiques','Scientific references'),
('33 études','33 studies'),
# product/age card short titles + condition labels
('Enfants croquables','Chewable kids'),
('Côlon irritable','Irritable bowel'),
('Gastro-intestinal','Gastrointestinal'),
('Infection urinaire','Urinary tract infection'),
('Infection à levure','Yeast infection'),
('Vaginose bactérienne','Bacterial vaginosis'),
('Canneberges','Cranberries'),
('Antibiothérapie','Antibiotic therapy'),
('Extra-fort','Extra-Strength'),
('Voyageurs','Travelers'),
('50 ans et +','50+'),
('Adultes','Adults'),
('réf. ','ref. '),
]
# sort longest FR first to avoid partial overlaps
P.sort(key=lambda x: -len(x[0]))
s=_en.chrome(open('choisir.html',encoding='utf-8').read())
miss=[]
for a,b in P:
    if a in s: s=s.replace(a,b)
    else: miss.append(a[:45])
open('en/choisir.html','w',encoding='utf-8').write(s)
print('choisir MISSES:',miss if miss else 'none')
